apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: healthcare-gen

resources:
  - namespace.yaml
  - configmap.yaml
  - secret.yaml
  - webui.yaml
  - epic-generator.yaml
  - network-generator.yaml

commonLabels:
  app.kubernetes.io/part-of: healthcare-observability-generator
