apiVersion: apps/v1
kind: Deployment
metadata:
  name: network-generator
  namespace: healthcare-gen
  labels:
    app: network-generator
    app.kubernetes.io/part-of: healthcare-observability-generator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: network-generator
  template:
    metadata:
      labels:
        app: network-generator
    spec:
      imagePullSecrets:
        - name: acr-secret
      containers:
        - name: network
          image: vietregistry.azurecr.io/healthcare-gen/network:latest
          imagePullPolicy: Always
          args:
            - "--config"
            - "/app/config/hospital/topology.yaml"
            - "--output"
            - "both"
            - "--mode"
            - "realtime"
            - "--tick-interval"
            - "60"
          envFrom:
            - configMapRef:
                name: generator-config
            - secretRef:
                name: dt-credentials
          resources:
            requests:
              cpu: 200m
              memory: 256Mi
            limits:
              cpu: 1000m
              memory: 1Gi
